name: Buildfish build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update submodules
      run: git submodule sync --recursive && git submodule update --init --force --recursive --depth=1

    - name: Build armv7hl
      id: build_armv7hl
      uses: attah/buildfish@0.9
      with:
        release: 3.3.0.14

    - name: Post
      run: ls RPMS
