
name: Buildfish build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 3.3.0.14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update submodules
      run: git submodule sync --recursive && git submodule update --init --force --recursive --depth=1

    - name: Prepare
      run: mkdir output

    - name: Build armv7hl
      id: build_armv7hl
      uses: attah/buildfish@0.3
      with:
        release: latest
      # run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
      #       mkdir -p build ;
      #       cd build ;
      #       cp -r /share/* . ;
      #       mb2 -t SailfishOS-$RELEASE-armv7hl build ;
      #       sudo cp -r RPMS/*.rpm /share/output"
